var app = angular.module('graphidh', []);

var arrayedos = [
  {name: "Aguascalientes",    value:  Math.random(), abrv: "Ags."},
  {name: "Baja California",    value:  Math.random(), abrv: "B.C."},
  {name: "Baja California Sur",     value: Math.random(), abrv: "B.C.S."},
  {name: "Campeche",   value: Math.random(), abrv: "Camp."},
  {name: "Chiapas", value: Math.random(), abrv: "Chia."},
  {name: "Chihuahua",     value: Math.random(), abrv: "Chih."},
  {name: "Ciudad de México",    value:  Math.random(), abrv: "Cd. Mex."},
  {name: "Coahuila",    value:  Math.random(), abrv: "Coah."},
  {name: "Colima",     value: Math.random(), abrv: "Col."},
  {name: "Durango",   value: Math.random(), abrv: "Dgo."},
  {name: "Guanajuato", value: Math.random(), abrv: "Gto." },
  {name: "Guerrero",     value: Math.random(), abrv: "Gro."},
  {name: "Hidalgo",    value:  Math.random(), abrv: "Hgo."},
  {name: "Jalisco",    value:  Math.random(), abrv: "Jal."},
  {name: "Edo. de México",     value: Math.random(), abrv: "Edo. Mex."},
  {name: "Michoacán",   value: Math.random(), abrv: "Mich."},
  {name: "Morelos", value: Math.random(), abrv: "Mor."},
  {name: "Nayarit",     value: Math.random(), abrv: "Nay."},
  {name: "Nuevo León",    value:  Math.random(), abrv: "N.L."},
  {name: "Oaxaca",    value:  Math.random(), abrv: "Oax."},
  {name: "Puebla",     value: Math.random(), abrv: "Pue."},
  {name: "Querétaro",   value: Math.random(), abrv: "Qro."},
  {name: "Quintana Roo", value: Math.random(), abrv: "Q. Roo"},
  {name: "San Luis Potosí",     value: Math.random(), abrv: "S.L.P."},
  {name: "Sínaloa",     value: Math.random(), abrv: "Sin."},
  {name: "Sonora",   value: Math.random(), abrv: "Son."},
  {name: "Tabasco", value: Math.random(), abrv: "Tab."},
  {name: "Tamaulipas",     value: Math.random(), abrv: "Tamps."},
  {name: "Tlaxcala",    value:  Math.random(), abrv: "Tlax."},
  {name: "Veracruz",    value:  Math.random(), abrv: "Ver."},
  {name: "Yucatán",     value: Math.random(), abrv: "Yuc."},
  {name: "Zacatecas",   value: Math.random(), abrv: "Zac"},
];

var arrayedos2016 = [
  {name: "Aguascalientes",    value:  Math.random(), idhyear: 2016},
  {name: "Baja California",    value:  Math.random(), idhyear: 2016},
  {name: "Baja California Sur",     value: Math.random(), idhyear: 2016},
  {name: "Campeche",   value: Math.random(), idhyear: 2016},
  {name: "Chiapas", value: Math.random(), idhyear: 2016},
  {name: "Chihuahua",     value: Math.random(), idhyear: 2016},
  {name: "Ciudad de México",    value:  Math.random(), idhyear: 2016},
  {name: "Coahuila",    value:  Math.random(), idhyear: 2016},
  {name: "Colima",     value: Math.random(), idhyear: 2016},
  {name: "Durango",   value: Math.random(), idhyear: 2016},
  {name: "Guanajuato", value: Math.random(), idhyear: 2016},
  {name: "Guerrero",     value: Math.random(), idhyear: 2016},
  {name: "Hidalgo",    value:  Math.random(), idhyear: 2016},
  {name: "Jalisco",    value:  Math.random(), idhyear: 2016},
  {name: "Edo. de México",     value: Math.random(), idhyear: 2016},
  {name: "Michoacán",   value: Math.random(), idhyear: 2016},
  {name: "Morelos", value: Math.random(), idhyear: 2016},
  {name: "Nayarit",     value: Math.random(), idhyear: 2016},
  {name: "Nuevo León",    value:  Math.random(), idhyear: 2016},
  {name: "Oaxaca",    value:  Math.random(), idhyear: 2016},
  {name: "Puebla",     value: Math.random(), idhyear: 2016},
  {name: "Querétaro",   value: Math.random(), idhyear: 2016},
  {name: "Quintana Roo", value: Math.random(), idhyear: 2016},
  {name: "San Luis Potosí",     value: Math.random(), idhyear: 2016},
  {name: "Sínaloa",     value: Math.random(), idhyear: 2016},
  {name: "Sonora",   value: Math.random(), idhyear: 2016},
  {name: "Tabasco", value: Math.random(), idhyear: 2016},
  {name: "Tamaulipas",     value: Math.random(), idhyear: 2016},
  {name: "Tlaxcala",    value:  Math.random(), idhyear: 2016},
  {name: "Veracruz",    value:  Math.random(), idhyear: 2016},
  {name: "Yucatán",     value: Math.random(), idhyear: 2016},
  {name: "Zacatecas",   value: Math.random(), idhyear: 2016},
];

var arrayedos2015 = [
  {name: "Aguascalientes",    value:  Math.random(), idhyear: 2015},
  {name: "Baja California",    value:  Math.random(), idhyear: 2015},
  {name: "Baja California Sur",     value: Math.random(), idhyear: 2015},
  {name: "Campeche",   value: Math.random(), idhyear: 2015},
  {name: "Chiapas", value: Math.random(), idhyear: 2015},
  {name: "Chihuahua",     value: Math.random(), idhyear: 2015},
  {name: "Ciudad de México",    value:  Math.random(), idhyear: 2015},
  {name: "Coahuila",    value:  Math.random(), idhyear: 2015},
  {name: "Colima",     value: Math.random(), idhyear: 2015},
  {name: "Durango",   value: Math.random(), idhyear: 2015},
  {name: "Guanajuato", value: Math.random(), idhyear: 2015},
  {name: "Guerrero",     value: Math.random(), idhyear: 2015},
  {name: "Hidalgo",    value:  Math.random(), idhyear: 2015},
  {name: "Jalisco",    value:  Math.random(), idhyear: 2015},
  {name: "Edo. de México",     value: Math.random(), idhyear: 2015},
  {name: "Michoacán",   value: Math.random(), idhyear: 2015},
  {name: "Morelos", value: Math.random(), idhyear: 2015},
  {name: "Nayarit",     value: Math.random(), idhyear: 2015},
  {name: "Nuevo León",    value:  Math.random(), idhyear: 2015},
  {name: "Oaxaca",    value:  Math.random(), idhyear: 2015},
  {name: "Puebla",     value: Math.random(), idhyear: 2015},
  {name: "Querétaro",   value: Math.random(), idhyear: 2015},
  {name: "Quintana Roo", value: Math.random(), idhyear: 2015},
  {name: "San Luis Potosí",     value: Math.random(), idhyear: 2015},
  {name: "Sínaloa",     value: Math.random(), idhyear: 2015},
  {name: "Sonora",   value: Math.random(), idhyear: 2015},
  {name: "Tabasco", value: Math.random(), idhyear: 2015},
  {name: "Tamaulipas",     value: Math.random(), idhyear: 2015},
  {name: "Tlaxcala",    value:  Math.random(), idhyear: 2015},
  {name: "Veracruz",    value:  Math.random(), idhyear: 2015},
  {name: "Yucatán",     value: Math.random(), idhyear: 2015},
  {name: "Zacatecas",   value: Math.random(), idhyear: 2015},
];

var years = [2017, 2016, 2015];

var sortData = ["Ascendente (A - Z)", "Descendente (Z - A)"];
